services:
    - docker:dind

image: docker:cli

stages:
    - checks
    - build
    - deploy

variable checking:
    stage: checks
    script:
        - |
            check_variable() {
              if [ -z "$1" ]; then
             echo "Error: environment variable is not set."
             exit 1
              fi
            }

        - check_variable "$SERVER_RUN"
        - check_variable "$SERVER_COPY"
        - check_variable "$SERVER_PATH"
        - check_variable "$DOCKER_USERNAME"
        - check_variable "$DOCKER_ACCESS_TOKEN"

deployment date:
    stage: checks
    before_script:
        - apk add --no-cache tzdata
    script:
        - export TZ=Asia/Kolkata
        - now=$(date "+%Y-%m-%d %I:%M %p %Z")
        - sed -i "s|%date%|$now|g" src/components/NavBar.jsx
    artifacts:
        paths:
            - src/components/
    allow_failure: true

docker build:
    stage: build
    script:
        - docker compose build
        - echo $DOCKER_ACCESS_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin
        - docker compose push
    dependencies:
        - deployment date

deploy to EC2:
    stage: deploy
    before_script:
        - chmod 400 $SERVER_KEY
    script:
        - $SERVER_COPY ./docker-compose.yml $SERVER_PATH
        - $SERVER_RUN "sudo docker compose down"
        - $SERVER_RUN "sudo docker compose pull"
        - $SERVER_RUN "sudo docker compose up -d"
        - $SERVER_RUN "rm ~/docker-compose.yml"
